export const LOAD_TODO = 'LOAD_TODO';
export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS';
export const LOAD_TODO_FAIL = 'LOAD_TODO_FAIL';

export const POST_TODO = 'POST_TODO';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
export const POST_TODO_FAIL = 'POST_TODO_FAIL';

export const PUT_TODO = 'PUT_TODO';
export const PUT_TODO_SUCCESS = 'PUT_TODO_SUCCESS';
export const PUT_TODO_FAIL = 'PUT_TODO_FAIL';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const SHOW_OPEN_TASKS = 'SHOW_OPEN_TASKS';

export const SHOW_COMPLETED_TASKS = 'SHOW_COMPLETED_TASKS';
